name: Push mvn Artifacts to JFrog Artifactory

on:
  push:
    branches:
      - master

env:
  JFROG_USERNAME: ${{ secrets.JF_USER }}
  JFROG_PASSWORD: ${{ secrets.JF_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure Maven settings
        run: |
          echo "<settings><servers><server><id>jfrog</id><username>${env.JFROG_USERNAME}</username><password>${env.JFROG_PASSWORD}</password></server></servers></settings>" > $HOME/.m2/settings.xml
      - name: Build and deploy artifacts to Artifactory
        run: mvn deploy
