name: Build and Publish Artifacts to JFrog

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Publish to JFrog
        uses: jfrog/setup-jfrog-cli@v1
        with:
          jfrog-url: 'https://arkoartifact.jfrog.io/'
          jfrog-username: ${{ secrets.JF_USER }}
          jfrog-password: ${{ secrets.JF_PASSWORD }}
      - run: |
          jfrog rt upload \
          --url ${{ secrets.JFROG_URL }} \
          --user ${{ secrets.JFROG_USERNAME }} \
          --password ${{ secrets.JFROG_PASSWORD }} \
          build/libs/*.jar test_artifact/
