# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example

on:
  workflow_dispatch:

jobs:
       
  build_and_upload:
    - name: Checkout project
      uses: actions/checkout@v2
      
    - name: Build image
      run: |
        docker build -t test_image:latest -<<EOF
        FROM busybox
        RUN touch abc.txt
        EOF

    - name: Upload image
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: "test_image:latest"
    
    - name: Use the Upload Artifact GitHub Action
      uses: ruben-baez-mojix-com/jfrog-deployment@v1.0.2
      with:
           # Jfrog username
        username: ${{ secrets.JF_USER }}
           # Jfrog password
        password: ${{ secrets.JF_PASSWORD }}
           # Artifact name
        artifact: test_image
           # URL where artifact will be deployed
        url: ${{ secrets.JF_URL }}
