name: Build and Publish Docker Images to JFrog

on:
  push:
    branches:
      - master
      
env:
  DOCKER_IMAGE_NAME: "myimage"
  DOCKER_IMAGE_TAG: "latest"      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build and tag Docker image
        shell: sh
        run: |
          IMAGE_ID=$(docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} . 2>/dev/null | awk '/Successfully built/{print $NF}')
          echo "Image ID is $IMAGE_ID"
          echo "Tag name is $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG-$IMAGE_ID"
          docker tag $DOCKER_IMAGE_NAME arkoartifact.jfrog.io/artifactory/docker/${{ env.DOCKER_IMAGE_NAME }}
          
      - name: Login to JFrog Docker registry
        uses: jfrog/setup-jfrog-cli@v1
        with:
          jfrog-url: 'https://arkoartifact.jfrog.io/'
          jfrog-username: ${{ secrets.JF_USER }}
          jfrog-password: ${{ secrets.JF_PASSWORD }}
      - run: |
          docker login arkoartifact.jfrog.io/ \
          -u ${{ secrets.JF_USER }} \
          -p ${{ secrets.JF_PASSWORD }}
          
      - name: Push Docker image to JFrog registry
        run: |
          docker push arkoartifact.jfrog.io/artifactory/docker/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
