name: Build and Publish Docker Images to JFrog

on:
  push:
    branches:
      - master
      
env:
  DOCKER_IMAGE_NAME: "myimage"
  DOCKER_IMAGE_TAG: "1.0.0"      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to JFrog Docker registry
        uses: jfrog/setup-jfrog-cli@v2.4.1
        with:
          jfrog-url: 'https://arkoartifact.jfrog.io/'
          jfrog-username: ${{ secrets.JF_USER }}
          jfrog-password: ${{ secrets.JF_PASSWORD }}
      - run: |
          docker login arkoartifact.jfrog.io/ \
          -u ${{ secrets.JF_USER }} \
          -p ${{ secrets.JF_PASSWORD }}   
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .
          docker tag arkoartifact.jfrog.io/artifactory/dockertest/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} dockertest/ 
          docker push arkoartifact.jfrog.io/artifactory/dockertest/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
        
      - name: Build and tag Docker image
        shell: sh
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .
          docker tag ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} arkoartifact.jfrog.io/artifactory/dockertest/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
              
      - name: Push Docker image to JFrog registry
        shell: sh
        run: |
          docker push arkoartifact.jfrog.io/artifactory/dockertest/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
